"""Add is_active to Customer model

Revision ID: 3f2baf381a41
Revises: 4ac470981dab
Create Date: 2025-12-07 20:09:18.939477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2baf381a41'
down_revision = '4ac470981dab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1. Adiciona a coluna is_active permitindo valores nulos (nullable=True)
    op.add_column('customers', sa.Column('is_active', sa.Boolean(), nullable=True))

    # 2. Define o valor TRUE para todos os clientes existentes
    # Isso garante que não haverá valores NULL ao aplicar a restrição NOT NULL.
    op.execute("UPDATE customers SET is_active = TRUE WHERE is_active IS NULL")

    # 3. Altera a coluna para NOT NULL (obrigatório), corrigindo o erro
    op.alter_column('customers', 'is_active', nullable=False, existing_type=sa.Boolean())

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'is_active')
    # ### end Alembic commands ###